cheDomain: 192.168.99.100.nip.io
isHostBased: true
tlsEnabled: false

# the following section is for secure registries. when uncommented, a pull secret will be created
#registry:
#  host: my-secure-private-registry.com
#  username: myUser
#  password: myPass

cheImage: eclipse/che-server:nightly
cheImagePullPolicy: Always
