{{- if and .Values.global.tls }}
{{- if and .Values.global.tls.enabled .Values.global.tls.useCertManager }}
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: che-host-cert
spec:
  secretName: {{ .Values.global.tls.secretName }}
  issuerRef:
    name: letsencrypt
  commonName: {{ template "cheHost" . }}
  dnsNames:
      - {{ template "cheHost" . }}
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - {{ template "cheHost" . }}
{{- end }}
{{- end }}