{{- if .Values.tlsEnabled }}
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: che-host-cert
spec:
  secretName: che-tls
  issuerRef:
    name: letsencrypt
  commonName: {{ .Values.cheDomain }}
  dnsNames:
      - {{ .Values.cheDomain }}
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - {{ .Values.cheDomain }}
{{- end }}
