#
# Copyright (c) 2022-2023 Red Hat, Inc.
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#
schemaVersion: 2.2.0
metadata:
  name: che
components:
- name: devtools
  container:
    image: quay.io/devfile/universal-developer-image:ubi8-latest
    memoryLimit: 12G
    memoryRequest: 256Mi
    cpuLimit: '2'
    cpuRequest: 30m
commands:
- id: update-contributing
  exec:
    commandLine: '.repositories-update-contributing.sh IN_DOCKER'
    component: devtools
- id: check-contributing-is-updated
  exec:
    commandLine: '.repositories-update-contributing.sh IN_DOCKER'
    component: devtools
