apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: keycloak-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: "nginx"
{{- if .Values.global.tlsEnabled }}
    kubernetes.io/tls-acme: "true"
{{- else }}
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
{{- end }}
    ingress.kubernetes.io/proxy-read-timeout: "3600"
    ingress.kubernetes.io/proxy-connect-timeout: "3600"
spec:
{{- if .Values.global.tlsEnabled }}
  tls:
  - hosts:
    - {{ template "keycloakHost" . }}
    secretName: keycloak-tls
{{- end }}
  rules:
  - host: {{ template "keycloakHost" . }}
    http:
      paths:
      - backend:
          serviceName: keycloak
          servicePort: 5050
        path: /
