apiVersion: batch/v1
kind: Job
metadata:
  name: keycloak-configure-job
spec:
  template:
    spec:
      initContainers:
      - name: wait-for-keycloak
        image: docker.io/guydaich/che-init
        command: ["sh", "-c", "adresses_length=0; until [ $adresses_length -gt 0 ]; do echo waiting for keycloak to be ready...; sleep 2; endpoints=`curl -s --cacert /var/run/secrets/kubernetes.io/serviceaccount/ca.crt -H \"Authorization: Bearer $(cat /var/run/secrets/kubernetes.io/serviceaccount/token)\"     https://kubernetes.default/api/v1/namespaces/$POD_NAMESPACE/endpoints/keycloak`; adresses_length=`echo $endpoints | jq -r \".subsets[]?.addresses // [] | length\"`; done;"]
        env:
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
      containers:
      - name: keycloak-configure-job
        image: {{ .Values.image }}
        command: ["/scripts/keycloak_config.sh"]
        env:
          - name: HTTP_PROTOCOL
{{- if .Values.global.tlsEnabled }}
            value: "https"
{{- else }}
            value: "http"
{{- end }}
          - name: KC_HOST
            value:  {{ template "keycloakHost" . }}
          - name: CHE_KEYCLOAK_ADMIN_REQUIRE_UPDATE_PASSWORD
            value: {{ .Values.requireAdminPasswordChange | quote }}

      restartPolicy: Never
  backoffLimit: 4