################################################################
# Global configuration
################################################################

debug = false
logLevel = "INFO"
[traefikLog]
  filePath = "/home/user/agent/traefik/traefik.log"
[accessLog]
  filePath = "/home/user/agent/traefik/access.log"


# Entrypoints to be used by frontends that do not specify any entrypoint.
# Each frontend can specify its own entrypoints.
#
# Optional
# Default: ["http"]
#
defaultEntryPoints = ["http"]

# Entrypoints definition
#
# Optional
# Default:
[entryPoints]
    [entryPoints.http]
    address = ":8085"
    [entryPoints.http2]
    address = ":8087"

################################################################
# Web configuration backend
################################################################

# Enable web configuration backend
#[web]

# Web administration port
#
# Required
#
#address = ":8086"



[file]

[backends]
  [backends.ide]
      [backends.ide.servers.server1]
             url = "http://localhost:8080"
  [backends.chemaster]
        [backends.chemaster.servers.server1]
             url = "http://che-host:8080"
[frontends]
  [frontends.liveness]
    priority = 20
    backend = "ide"
    passHostHeader = true
    entrypoints = ["http2"]
    [frontends.liveness.routes.api_workspace]
    rule = "PathPrefix:/api/liveness"
  [frontends.api]
    backend = "chemaster"
    priority = 19
    passHostHeader = true
    [frontends.api.headers.customrequestheaders]
      Authorization = 'Bearer che_machine_token_placeholder'
    [frontends.api.routes.api]
    rule = "PathPrefix:/api"
  [frontends.api_entrypoint]
    priority = 15
    backend = "chemaster"
    passHostHeader = true
    [frontends.api_entrypoint.redirect]
      regex = "^(http|https)://(.*)/gwt/ide/sidecar/entrypoint/api/(.*)"
      replacement = "$1://$2/api/$3"
    [frontends.api_entrypoint.routes.ide]
      rule = "PathPrefix:/api/"
  [frontends.frontend1]
    priority = 10
    backend = "ide"
    passHostHeader = true
    [frontends.frontend1.redirect]
      regex = "^(http|https)://(.*)/gwt/ide/sidecar/entrypoint"
      replacement = "$1://$2/che_workspace_namespace_placeholder/che_workspace_name_placeholder"
    [frontends.frontend1.routes.ide]
      rule = "PathPrefix:/; AddPrefix:/ide"
  [frontends.workspace-loader]
    priority = 10
    backend = "ide"
    passHostHeader = true
    [frontends.workspace-loader.redirect]
      regex = "^(http|https)://(.*)/workspace-loader/che_workspace_namespace_placeholder/che_workspace_name_placeholder"
      replacement = "$1://$2/che_workspace_namespace_placeholder/che_workspace_name_placeholder"
    [frontends.workspace-loader.routes.ide]
      rule = "PathPrefix:/; AddPrefix:/ide"
  [frontends.loader]
    priority = 5
    backend = "ide"
    passHostHeader = true
    [frontends.loader.redirect]
      regex = "^(http|https)://(.*)/_app/loader.html"
      replacement = "$1://$2/"
    [frontends.loader.routes.ide]
      route = "PathPrefix:/"
  [frontends.default]
    backend = "ide"
    passHostHeader = true
    entrypoints = ["http2"]
