# Documentation in https://dependabot.com/docs/config-file/
version: 2
updates:
  - package-ecosystem: docker
    directory: "/dockerfiles/postgres"
    schedule:
      interval: daily
      time: "03:00"
    open-pull-requests-limit: 10
    labels:
      - area/dependencies
    allowed_updates:
      - match:
          update_type: "security"
  - package-ecosystem: docker
    directory: "/dockerfiles/keycloak"
    schedule:
      interval: daily
      time: "03:00"
    allowed_updates:
      - match:
          update_type: "security"
    open-pull-requests-limit: 10
    labels:
      - area/dependencies
  - package-ecosystem: docker
    directory: "/dockerfiles/che"
    schedule:
      interval: daily
      time: "03:00"
    allowed_updates:
      - match:
          update_type: "security"
    open-pull-requests-limit: 10
    labels:
      - area/dependencies
  - package-ecosystem: maven
    directory: "/"
    schedule:
      interval: daily
      time: "03:00"
    allowed_updates:
      - match:
          update_type: "security"
    open-pull-requests-limit: 10
    labels:
      - area/dependencies