#
# Copyright (c) 2021 Red Hat, Inc.
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#

name: build-nightly

on:
  workflow_dispatch:
  schedule:
  - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Cache local Maven repository
      uses: actions/cache@v2
      with:
       path: ~/.m2/repository
       key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
       restore-keys: |
        ${{ runner.os }}-maven-      
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11.0.11+9'
    - name: Login to docker.io
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
        registry: docker.io
    - name: Login to quay.io
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.QUAY_USERNAME }}
        password: ${{ secrets.QUAY_PASSWORD }}
        registry: quay.io
    - name: Build docker images
      id: build
      run: |
          SHORT_SHA1=$(git rev-parse --short HEAD)
          echo ::set-output name=short_sha1::${SHORT_SHA1}
          docker build -t quay.io/eclipse/che-e2e:nightly dockerfiles/e2e/
          docker tag quay.io/eclipse/che-e2e:nightly quay.io/eclipse/che-e2e:${SHORT_SHA1}
    - name: Push docker images
      run: |
        docker push quay.io/eclipse/che-server:nightly
        docker push quay.io/eclipse/che-server:${{ steps.build.outputs.short_sha1 }}
    - name: Create failure MM message
      if: ${{ failure() }}
      run: |
        echo "{\"text\":\":no_entry_sign: Nightly Che build has failed: https://github.com/eclipse/che/actions/workflows/next-build.yml\"}" > mattermost.json
    - name: Send MM message
      if: ${{ failure() }}
      uses: mattermost/action-mattermost-notify@1.0.2
      env:
        MATTERMOST_WEBHOOK_URL: ${{ secrets.MATTERMOST_WEBHOOK_URL }}
        MATTERMOST_CHANNEL: eclipse-che-ci
        MATTERMOST_USERNAME: che-bot
